### ISSUE TITLE
Foliage renders nothing after a tessellated-terrain evidence test: deterministic cross-test state leak, 0% subject coverage

### ISSUE THREAD

**Issue by drsnuggles8** [drsnuggles8/OloEngineBase#1315]
## What

`FoliageWindEvidenceTest.EveryRasterPathShowsWindAndMotion` renders **no foliage at all** — 0% plant coverage, on every rendering path — when a tessellated-terrain evidence test has run earlier in the same process. It passes in isolation, so the failure only shows up in a full-suite sweep, where it reads as an unexplained golden delta rather than as "the subject vanished".

This is a **cross-test state leak, not a flake**: it is fully deterministic given the ordering.

## Reproducer — 30 seconds, two suites

```powershell
build\OloEngine\tests\Debug\OloEngine-Tests.exe `
  --gtest_filter="TerrainCameraRelativeVisualEvidenceTest.*:FoliageWindEvidenceTest.EveryRasterPathShowsWindAndMotion"
```

```
VisualEvidenceGuards.cpp(75): error: Expected: (coverage) >= (minCoverage), actual: 0 vs 0.002
pose 'Ground': the content mask found 0% of the frame, below the 0.2% floor — the subject is not on screen.
FoliageWindEvidenceTest.cpp(190): error: Rgba8Ssim(flipped, baseline) >= 0.985, actual: 0.7157
```

**Two independent triggers**, each sufficient on its own:

- `TerrainCameraRelativeVisualEvidenceTest.*`
- `TerrainGPUQuadtreeVisualEvidenceTest.*`

Clean (do **not** trigger it): `TerrainGenerationEvidenceTest`, `DriftIslandFieldEvidenceTest`, and every `*Foliage*` suite — `--gtest_filter=*Foliage*` alone is 117 tests, all green.

## What the frame actually looks like

Regenerate both with `--olo-golden-rebase` on the filter above and compare against the committed
`OloEditor/assets/tests/visual/FoliageWind_GL_Forward_MSAA1_Ground.png`:

- **Committed golden:** a dense field of grass/plants over patchy terrain.
- **After a terrain evidence test:** the identical terrain, identical lighting, identical splat
  pattern — and **not one plant**. The scene is otherwise pixel-plausible, which is why an SSIM
  number (0.95 in a full sweep, 0.70 in the minimal pair) was the only symptom anyone saw.

The severity is badly understated by the metric: this is not shading drift, it is the entire
subject missing.

## Ruled out, by measurement

- **Wind phase accumulation.** `WindSystem::s_Data.m_AccumulatedTime` is a process-global that only
  `Init`/`Shutdown` reset — a good suspect, but wrong: `--gtest_repeat=2` on the foliage test alone
  passes both iterations, so an advanced accumulator does not by itself break it.
- **Render origin / camera-relative.** `ComputeRenderOrigin` is a pure function of the camera
  position and returns exactly `(0,0,0)` inside the first 1024-unit cell; the foliage camera is at
  `(128, 12, 150)`. Also, only one of the two triggers goes far from the origin at all
  (`kFarShift = 45056`), so a far-origin residue is not the common factor.
- **Renderer configuration leaks.** `--olo-strict-renderer-state` flags many tests in this range
  (`WaterDisturbanceSettings`, `WaterWakeSettings`, `CloudscapeRenderState`, `UnderwaterFogState`),
  but the #1074 listener *restores* every one of them, so they cannot be the corruptor. Neither
  trigger is flagged for anything the foliage path reads.
- **`TerrainChunkManager::s_GpuDrivenLODEnabled`.** A genuine process-global, but its default is
  `true` and `TerrainGPUQuadtreeVisualEvidenceTest` ends by setting it back to `true`, so it is
  restored. The other trigger never touches it.

## What the triggers share

Both build a **procedural terrain with `m_TessellationEnabled = true`** plus auto-material /
auto-splat, and run editor frames through it. `TerrainGenerationEvidenceTest`, which builds terrain
*without* that path, does not trigger it. That points at state owned by the tessellated /
quadtree LOD terrain path that outlives its scene and that the later foliage scatter or foliage
draw depends on — but the actual owner was not identified.

## Why it matters

The class is the one `world-anchored-renderer-state-in-tests.md` and
`docs/agent-rules/testing-architecture.md` §6 already describe, but this instance is worse than the
documented ones: the guard that caught it (`ExpectFrameHasSubject`, issue #931) only fires because
someone added a content-mask floor. Without it the test would have compared two plant-free frames
to each other and passed.

It also makes the full-suite sweep unusable as a pre-push gate: this is currently the **only**
failure in an 8845-test run, so it trains everyone to ignore that run's one red line.

## Not caused by, but found during, #1300 / PR #1309

PR #1309 (Vulkan test coverage) does not touch foliage, terrain or any rendering code. The
`FoliageWind_*` goldens were last regenerated by `6b7c97132` ("feat(foliage): share hierarchical
wind across raster and motion paths", PR #1303), which is an **ancestor** of that branch's base
`3b2e23aeb`; and the reproducing filter above contains no test that PR modifies.

## Suggested shape of a fix

Find the owner first — a speculative reset in the foliage fixture would paper over it. Once found,
either restore it at its source (the rule the `--olo-strict-renderer-state` message already states)
or extend the #1074 `RendererState` listener to cover it, so the next such global is caught by
accounting rather than by a golden.

```olo-score
capability: 3
craft: 2
stability: 8
decay: 6
effort: 3
confidence: 0.7
learning: 5
fun: 4
kano: table-stakes
blocked_by: []
blocks: []
```

**Comment by drsnuggles8** [comment]
Root cause found and fixed in #1319 — and it is not a terrain state leak.

**Owner:** `Renderer3D::RenderPipeline::ComputeBlackboardFingerprint` did not hash whether `FoliageRenderPass` has draws this frame, while `FoliageRenderPass::Setup` returns without declaring any graph access when its command bucket is empty. `BuildFrameGraph` skips every pass's `Setup()` on a fingerprint hit, so a graph compiled during a terrain-only frame caches a foliage node with no reads and no writes, reachability culls it, and nothing about plants appearing moves the fingerprint again.

The capture that settled it — a probe on `Setup`, `Execute` and the fingerprint:

```
OLO1315 Setup:   commands=0            <- graph compiled here, pass declared nothing
OLO1315 submit:  layerInfos=2 canonical=1310 mesh=1310 vao=true indirect=true   <- x28 frames
                                        (no Execute line anywhere)
OLO1315 Setup:   commands=2            <- the path switch finally moved the fingerprint
```

Every producer-side number was correct: 1310 instances generated, culled and submitted every frame. `FoliageRenderPass::Execute` was never called.

**Three corrections to this issue, all measured:**

1. **Not "0% on every raster path".** All 13 failures are in the first cell, `Forward samples=1`. The switch to Forward+ moves the fingerprint, `Setup()` re-runs, and the remaining cells are perfect. A bug that heals partway through its own reproducer is what made the state look transient.
2. **Terrain is incidental.** `OLO_FOLIAGE_CPU_CULL=1` and `OLO_TERRAIN_CPU_LOD=1` both still reproduce, so #1235's GPU cull and #714's GPU descent are exonerated. The trigger is only "a scene that rendered a frame with the foliage bucket empty at a matching fingerprint".
3. **A third trigger exists** and was not listed here: `TerrainGPUBrushVisualEvidenceTest`. Same fix covers it.

Resolution was tessellation, though — the `960x540` correlation I chased first was a red herring, killed by `VoxelGreedyMeshVisualEvidenceTest` (960x540, tessellation off) staying clean.

**Fix:** three `HashBool` lines, mirroring the one `WaterRenderPass` already had. `DecalRenderPass` and `ForwardOverlayRenderPass` had the identical hole and are fixed with it. Groom was already covered by #1246 — which is the finding worth keeping: every fix of this class so far saw only its own pass, so #1319 adds `docs/agent-rules/render-graph-setup-declaration-gates.md` and a pure-CPU accounting test (`RenderGraphFingerprint.EveryBucketGatedStreamPassChangesFingerprintOnFirstDraw`) over the whole set, per this issue's closing paragraph.

**Verification:** 1,256 tests across 10 ordering cells, zero failures — all three triggers now green, both known-clean controls still clean, and the guard proven non-vacuous (with only the fix reverted it fails on Foliage/Decal/ForwardOverlay and passes on Water).

Recommending closure on merge of #1319; leaving that to you.
