### ISSUE TITLE
Flaky test: UnderwaterCausticsVisualTest fails on leaked GL_INVALID_VALUE from a prior GPU test (order-dependent)

### ISSUE THREAD

**Issue by drsnuggles8** [drsnuggles8/OloEngineBase#625]
**Describe the bug**
`UnderwaterCausticsVisualTest.CausticsBrightenAndTextureTheSeabed` is an **order-dependent flake**: it fails when run in a large GPU-test batch but passes in isolation and in small batches. The failure is not in the test's own assertions (seabed brightness / caustic variance) — it is a **leaked GL error** caught by the `RendererAttachedTest` post-frame guard:

```
RendererAttachedTest.cpp(49): error: Failed
RendererAttachedTest::RunEditorFrames render tick left a GL error: GL_INVALID_VALUE
(the whole error queue is drained so the next test starts clean).
```

**Root cause (likely)**
The GPU tests share one process-wide GL context. Some earlier test issues a call that raises `GL_INVALID_VALUE` and finishes **without draining `glGetError()`**. The error sits in the shared context's error queue until the next `RendererAttachedTest` runs a render tick; that fixture calls `glGetError()` after the tick (`RendererAttachedTest.cpp:49`), sees the stale error, and fails the *innocent* next test — here `CausticsBrightenAndTextureTheSeabed`, which just happens to be the next visual test in the batch. The fixture drains the queue on the way out, so re-running the single test passes.

**Not caused by #440.** Found while verifying the texture-compression work: the caustics test fails in the `--gtest_filter='*AssetPack*:*Serializ*:*Texture*:*AssetSerial*'` sweep, but passes both standalone and in `CompressedTextureVisualEvidence.*:TextureAutoCookPackTest.*:...Caustics...` (the new compression GPU tests are clean and leave no GL error). The leaking test is some other GPU test pulled into the large sweep.

**To Reproduce**
1. `OloEngine-Tests.exe --gtest_filter='*AssetPack*:*Serializ*:*Texture*:*AssetSerial*'` → the caustics test fails with the GL_INVALID_VALUE message above.
2. `OloEngine-Tests.exe --gtest_filter='UnderwaterCausticsVisualTest.CausticsBrightenAndTextureTheSeabed'` → passes.
(Requires a GL 4.6 context; SKIPs headless.)

**Expected behavior**
A GL error leaked by one test must not fail an unrelated later test. Each visual test should be attributed only the GL errors its own render tick produced.

**Suggested fix**
1. **Make `RendererAttachedTest` isolation-robust:** drain `glGetError()` in a loop *before* the render tick in `RunFrames` / `RunEditorFrames` (not only after), so only errors the tick itself raised can fail the test. This is the cheap, high-leverage fix and hardens every visual test against upstream leakage.
2. **Find and fix the actual leaker:** bisect the sweep (e.g. `--gtest_filter` halving, or run with a per-test `glGetError()` drain-and-assert) to identify which test raises the un-drained `GL_INVALID_VALUE`, and drain/fix it at the source.

Both are worth doing — (1) stops the false failures now, (2) removes the underlying bug. Related hygiene notes: `docs/agent-rules/testing-architecture.md` and the `GLStateGuard` / process-wide `Renderer::Shutdown()` teardown pattern (issue #258).

**Screenshots / logs**
```
RendererAttachedTest.cpp(49): error: Failed
RendererAttachedTest::RunEditorFrames render tick left a GL error: GL_INVALID_VALUE
[  FAILED  ] UnderwaterCausticsVisualTest.CausticsBrightenAndTextureTheSeabed (1623 ms)
```

## Score
```olo-score
capability: 1
craft: 2
stability: 3
decay: 2
effort: 2
confidence: 0.8
learning: 2
fun: 2
kano: table-stakes
blocked_by: []
blocks: []
```

**Comment by drsnuggles8** [comment]
Root cause found and fixed in `2185e480` (branch `fix/flaky-underwater-caustics-625`) — **not** the `glLineWidth` lead from #601's review. That path (`Renderer2D::DrawLine`/`DrawRect`) turned out to be a dead end for this specific flake: it's only reachable from `EditorLayer`'s selection-outline gizmo and one test that already saves/restores the line width around it, so it's never exercised anywhere in the GPU test sweep. Still a latent core-profile hazard worth fixing separately, but it wasn't the source of this failure.

**Actual mechanism:**

`OpenGLShader`/`OpenGLComputeShader` delete their GL program via `FrameResourceManager`'s **deferred** deletion queue (drained a few frames later, at `BeginFrame()` — potentially many tests removed from whichever test destroyed the shader). If the program is still `GL_CURRENT_PROGRAM` at the moment that deferred `glDeleteProgram` finally runs, GL only *flags* it for deletion — the id stays valid and current until something else calls `glUseProgram`. Nothing in the fixture resets bindings between tests, so a transient shader that happened to be the last-bound program of its test can stay "current but delete-pending" across several subsequent (including headless) tests.

The landmine springs on the next GPU test's very first clear: `ShadowRenderPass::Execute` → `Utils::GLClearProgramGuard`, which saves `GL_CURRENT_PROGRAM` and unbinds for the duration of the clear. That unbind is what finally completes the already-flagged deletion. The guard's destructor then tries to **restore** the saved id — now genuinely deleted — and `glUseProgram` raises `GL_INVALID_VALUE ("Program handle does not refer to an object generated by OpenGL")`. This lands on whichever test renders next, which is why it looked order-dependent and pinned the blame on the innocent `UnderwaterCausticsVisualTest` rather than the actual (several-tests-earlier) source.

Confirmed via the synchronous GL debug callback's captured call stack, which pointed straight at `GLClearProgramGuard::~GLClearProgramGuard` inside `OpenGLRendererAPI::ClearDepthOnly`.

**Fix (both defense-in-depth):**
1. `Utils::UnbindProgramIfCurrent()` (`Platform/OpenGL/OpenGLUtilities.h`) — called immediately before every program-deletion site that can run while bound (both `OpenGLShader`/`OpenGLComputeShader` destructors and their hot-reload retire paths, 4 sites total), so the deletion is immediate and deterministic instead of a dangling flagged-for-deletion id.
2. `GLClearProgramGuard`'s destructor now checks `glIsProgram()` before restoring, as a guard against any similarly-shaped bug reaching it in the future.

**Note on the RendererAttachedTest pre-tick drain (part 1 of the suggested fix):** this was already in place on `master` (`RunGuardedRenderTick`'s pre-tick `GLErrorState::DrainAndGetFirstError` check, plus the global `GLErrorStateCheck` listener from #485) by the time this branch started — so only part 2, the actual leaker hunt, remained.

**Verified:** the repro sweep (`--gtest_filter='*AssetPack*:*Serializ*:*Texture*:*AssetSerial*'`, 272/272), the full suite (4347/4347), and two `--gtest_shuffle` seeds (1, 42) all pass clean with zero GL errors.

Lesson captured in `docs/agent-rules/testing-architecture.md` §6.6 and cross-linked from `docs/agent-rules/gl-clear-program-revalidation.md`.
