### ISSUE TITLE
FogVisualEvidenceTest.DistantGeometryFogsNearStaysClear fails in full suite (cumulative cross-test renderer state); passes in isolation

### ISSUE THREAD

**Issue by drsnuggles8** [drsnuggles8/OloEngineBase#446]
## Summary

`FogVisualEvidenceTest.DistantGeometryFogsNearStaysClear`
(`OloEngine/tests/Rendering/PropertyTests/FogVisualEvidenceTest.cpp`) **fails when
run as part of the full test suite but passes in isolation** (and in every
sub-range tried). It is an order-dependent / cumulative cross-test state bug — a
render that ran earlier in the process leaves global renderer state that makes
the fog effect render incorrectly much later.

This is **not** a fog *math* bug (the L-tier `FogMathTest` contracts pass) and is
unrelated to any current feature work — it reproduces on the base branch.

## Symptom

The test renders the same frozen scene twice (fog OFF, then fog ON) and asserts
the distant band gains blue fog:

```
FogVisualEvidenceTest.cpp(315): error: Expected: (farOn.B) > (farOff.B + 15.0),
  actual: 138.00776510006338 vs 153.00776510006338
```

`farOn.B == farOff.B` to 14 decimals → fog ON and OFF produce a **byte-identical**
far band, i.e. fog is (almost) not applied in the ON capture.

## Reproduction

```
# Fails (cumulative state):
OloEngine-Tests.exe --gtest_filter='<all suites 143..283 in run order>:FogVisualEvidenceTest.*'
# Passes:
OloEngine-Tests.exe --gtest_filter='FogVisualEvidenceTest.*'
```

No single predecessor reproduces it — bisecting the failing range, *every*
sub-range passes in isolation, only the full ~140-suite span fails. So the
corrupting state accumulates across many GPU-rendering tests rather than coming
from one culprit. (The fixture `RendererAttachedTest` restores `RendererSettings`
+ `PostProcessSettings` and re-applies them each teardown, but does **not** reset
the render graph's temporal history / per-frame fingerprint caches between tests.)

## Investigation (what was ruled in/out, via temporary GPU readback instrumentation)

Working forward from "fog ON ≡ fog OFF":

1. **Fog pass readiness** — `FogRenderPass::IsReadyForExecution()` is **never**
   false when enabled (shaders ready, PostProcess UBO bound). So `FogColor` is
   declared in `PopulateBlackboard`. ✗ not the cause.
2. **Graph wiring / culling** — `PopulateBlackboard` runs (declares `FogColor`),
   `BuildFrameGraph` **rebuilds** for the fog frames (fingerprints match between
   `PopulateBlackboard` and `BuildFrameGraph` — no single-slot cache desync), and
   the fog pass **executes** with all valid inputs
   (`input!=0, out, halfRes, depthValid`). ✗ not culled, not a cache desync.
3. **Downstream consumption** — `ToneMapRenderPass` *does* select `FogColor` as
   its input (`pickedFog=true`), so the fog output is composited. ✗ not a
   versioned-resource resolution miss.
4. **Fog output value** — reading back the fog pass's own output framebuffer:
   - isolation (pass): far band = `(0.20, 0.40, 0.90)` → **full** fog (== fog colour)
   - full suite (fail): far band = `(0.41, 0.45, 0.48)` → **~40%** fog
   So the fog is computed but **far-distance fog is under-applied**; after
   tone-mapping the weak gradient rounds to byte-identical with OFF. The *near*
   band is identical in both runs (correctly unfogged).
5. **Reconstruction inputs** — for `ExponentialSquared` fog,
   `factor = 1 - exp(-(density·dist)²)` (`FogCommon.glsl::computeDistanceFog`;
   `dist = distance(worldPos, cameraPos)`, `FogCommon`/`PostProcess_Fog.glsl`).
   density is set by the test (0.02). All of the following are **identical**
   between the passing and failing runs (verified by readback at fog Execute):
   - scene-depth **content** (far `0.999688`, near `0.993460`)
   - projection near/far (`0.05` / `999.88`) and `data.ProjectionMatrix`
   - the inverse-VP UBO at **binding 8** (MotionBlur UBO, same renderer id)
   - the camera UBO **buffer** at **binding 0** (same renderer id)

## Where the trail went cold

With identical depth + identical reconstruction matrices + identical bound UBOs,
the ExponentialSquared fog factor *should* be identical — yet it differs (full vs
~40%). That points at the effective camera→fragment **distance** differing, i.e.
the shared camera UBO's *contents* (`u_CameraPosition`, used directly at
`PostProcess_Fog.glsl` line 163 / 193) being **stale** at fog-execute time —
overwritten mid-frame by another pass (skybox / terrain / sky bake re-upload the
shared camera UBO; cf. the same-shaped hazard the binding-8 comment in
`RenderPipeline.cpp` ~L990 already warns about for the inverse-VP) and not
refreshed before the late post-process fog reads it. The contradiction is that a
wrong camera *position* would also fog the near band, which stays correct — so
either the stale value differs only subtly, or the actual culprit is some other
per-frame value that survives across tests. Reading binding-0's contents back
mid-render via `glGetNamedBufferSubData` returned the sentinel (call failed while
an FBO was bound), so the camera-position theory wasn't confirmed.

## Suggested next steps

1. Confirm/deny the stale-camera-position theory: log `u_CameraPosition` (or read
   binding-0 contents *outside* an active FBO) at fog Execute, full suite vs
   isolation.
2. If confirmed: have `FogRenderPass` (and the other binding-0 / binding-8
   consumers — deferred lighting, TAA, motion blur) **re-bind the shared camera
   UBO right before their draw** (the same fix already applied for binding 8 at
   `RenderPipeline.cpp` ~L997), rather than relying on a frame-start bind that a
   later/earlier pass can clobber.
3. Independently worth doing for test hygiene: have `RendererAttachedTest`
   teardown reset the render-pipeline temporal history + per-frame fingerprint
   caches (`RenderPipeline::Reset()` already zeroes `FogHistoryValid` /
   `TAAHistoryValid`) so GPU-rendering tests can't accumulate cross-test state.
   (This may or may not fix this specific test, but addresses the documented
   "states not reset between tests" hazard the suite has hit before, e.g. #258.)

## Workaround today

The test **passes in isolation**, so it gates correctly on a real GPU run of just
the fog suite; it only flips red in the full-suite run.

## Score
```olo-score
capability: 1
craft: 1
stability: 3
decay: 2
effort: 3
confidence: 0.5
learning: 3
fun: 3
kano: table-stakes
blocked_by: []
blocks: []
```
<sub>Rated per [issue-scoring](https://github.com/drsnuggles8/OloEngineBase/blob/master/docs/process/issue-scoring.md) · score = confidence × (capability + craft + stability + decay) / effort, derived by the picker.</sub>
